### ISSUE TITLE
Better error reporting when jsdoc is missing in tsconfig

### ISSUE THREAD

**Issue by jonaskello** [develar/ts2jsdoc#1]
Thanks for this tool, I this is a better idea than typedoc since you can use all jsdoc tools with this!

I tried it and I was missing the `jsdoc` attribute in `tsconfig.json` and got this error:
```
$ ts2jsdoc
TypeError: Cannot read property 'out' of undefined
    at /usr/local/lib/node_modules/ts-jsdoc/src/JsDocGenerator.ts:32:38
```

From this error it is not quite clear what you should do. So maybe add better checking and error message for missing jsdoc?

**Comment by jonaskello** [comment]
Also if the `tsconfig.json`file is missing the error is possible to understand but could be improved to not show a stack dump. Currently this happens:

```
$ ts2jsdoc
Error: ENOENT: no such file or directory, open '/XXXX/tsconfig.json'
    at /usr/local/lib/node_modules/ts-jsdoc/src/util.ts:41:71
    at Generator.next (<anonymous>)
```
